main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('video/<int:video_id>/', views.watch_video, name='watch_video'),
    path('video/add_comment/', views.add_comment, name='add_comment'),
    path('video/add_like/<int:video_id>/', views.add_like, name='add_like'),
    path('<str:session_username>/profile/', views.profile, name='profile'),
    path('<str:session_username>/dashboard/', views.dashboard, name='dashboard'),
    path('add_subscriber/<viewer>/', views.add_sub, name='add_subscriber'),
    path('upload/', views.upload_video, name='upload'),
    path('edit_video/<int:video_id>', views.edit_video, name='edit_video'),
    path('delete_video/', views.delete_video, name='delete_video'),
    path('update_details/', views.update_details, name='update_details'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('search/', views.search, name='search'),
]

news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Projectnews.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('edit/', views.edit, name='edit'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path
from products.views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page),
]

video_sharing/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "Viral Video Admin Panel"
admin.site.site_title = "Viral Video Admin Portal"
admin.site.index_title = "Welcome to Video Viral!"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class VideoPost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    desc = models.TextField()
    video_file = models.FileField(upload_to='videos/')
    thumbnail = models.ImageField(upload_to='videos/thumbnail/', default='none')
    category = models.CharField(max_length=50, default='none')
    pub_date = models.DateField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='likes')
    video_views = models.ManyToManyField(User, related_name='video_views')

    def __str__(self):
        return self.title




class UserData(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    about = models.TextField()
    profile_pic = models.ImageField(upload_to='pic/', default='pic/default.jpg')
    subscribers = models.ManyToManyField(User, related_name='subscribers')




class Comment(models.Model):
    post = models.ForeignKey(VideoPost, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=300)

    def __str__(self):
        return self.user.username

products/models.py
from django.db import models


# Создаем таблицу для Категории
class CategoryModel(models.Model):
    title = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


# Создаем таблицу для Продуктов
class ProductModel(models.Model):
    title = models.CharField(max_length=100, help_text='Тут вы должны писать название вашего продукта')
    price = models.FloatField()
    category = models.ForeignKey(CategoryModel, on_delete=models.CASCADE, null=True)
    image = models.FileField(upload_to='product_images')
    descriptions = models.TextField()
    count = models.IntegerField(default=0)
    link = models.TextField(null=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'


# Создать таблицу(модель) для корзины -> product, total_price, total_count, created_at
# class CartModel()

class CartModel(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    product_key = models.ForeignKey(ProductModel, on_delete=models.CASCADE, null=True)
    count = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Cart'
        verbose_name_plural = 'Carts'

class NewsCategory(models.Model):
    title = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'NewsCategory'
        verbose_name_plural = 'NewsCategories'


class News(models.Model):
    title = models.CharField(max_length=50)
    main_text = models.TextField()
    categoty_key = models.ForeignKey('NewsCategory', on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'News'
        verbose_name_plural = 'News'

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>Hello world!</h3>
</body>
</html>

templates/all-news.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
<main class="container mt-3 mb-5">
	<link rel="stylesheet" href="{% static 'style.css' %}">
	<h3 class="border-bottom pb-1 my-4">{{news.catgeory.title }}</h3>
	<!-- News Box -->
    {% for news in all_news %}
	<div class="card mb-4 shadow">
	  <div class="row no-gutters">
	    <div class="col-md-3">
	      <img src="/media/{{news.image}}" class="card-img" alt="{{news.title}}">
	    </div>
	    <div class="col-md-8">
	      <div class="card-body">
	        <h5 class="card-title">{{news.title}}</h5>
	        <p class="card-text">{{news.detail}}</p>
	        <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
	      </div>
	    </div>
	  </div>
	</div>
{% endfor %}
</main>
{% endblock%}
<script scr="{% static 'script.js' %}"></script>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}homepage {% endblock%}</title>
	<!-- Bootstrap 4 CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bs4/bootstrap.min.css ' %}" />
	<!-- Main Jquery -->
	<script type="text/javascript" src="{% static 'vendor/jquery.min.js' %} "></script>
	<!-- Bootstrap Js -->
	<script type="text/javascript" src="{% static '/vendor/bs4/bootstrap.min.js' %}"></script>
</head>
<link rel="stylesheet" href="{% static 'style.css' %}">
<body>
	<!-- Top News -->
	<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
		<div class="container">
		  <a class="navbar-brand" href="/">Cumwesu News</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNav">
		    <ul class="navbar-nav ml-auto">
		      <li class="nav-item active">
		        <a class="nav-link" href="/">Home</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'all-news' %}">All News</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'all-category' %}">All Categories</a>
		      </li>
				<li class="nav-item">
		         {% if user.is_authenticated %}
                        <a href="{% url 'dashboard' %}"><i class="fa fa-commenting-o"></i>{{ user.username }}</a>
                    {% else %}
                        <a href="{% url 'register' %}"><i class="fa fa-commenting-o"></i>Signup</a>
                    {% endif %}
		      </li>
		    </ul>
		  </div>
	  	</div>
	</nav>

{% block content %}
{% endblock%}

    <hr/>
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p>New to Bootstrap? <a href="https://getbootstrap.com/">Visit the homepage</a> or read our <a href="/docs/4.5/getting-started/introduction/">getting started guide</a>.</p>
  </div>
	<script scr="{% static 'script.js' %}"></script>
</footer>
</body>
</html>

templates/category-news.html
{% extends 'base.html' %}
{% block content%}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">{{category.title}}</h3>
	<!-- News Box -->
    {% for news in all_news %}
	<div class="card mb-4 shadow">
	  <div class="row no-gutters">
	    <div class="col-md-3">
	      <img src="/media/{{news.image}}" class="card-img" alt="{{news.title}}">
	    </div>
	    <div class="col-md-8">
	      <div class="card-body">
	        <h5 class="card-title">{{news.title}}</h5>
	        <p class="card-text">{{news.detail}}</p>
	        <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
	      </div>
	    </div>
	  </div>
	</div>
{% endfor %}
</main>
{% endblock%}

templates/category.html
{% extends 'base.html' %}
{% block content%}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">All Categories</h3>
	<div class="row">
		<!-- Category Box -->
	{% for cat in cats%}
		<div class="col-md-4">
			<div class="card mb-3 shadow">
			 <img src="/media/{{cat.category_image}}" class="card-img-top" alt="{{cat.title}}">
			
			  <div class="card-body">
			    <h5 class="card-title">{{cat.title }}</h5>
			    <hr/>
			    <p class="card-text"><a href="category/{{cat.id}}" class="btn btn-sm btn-primary">All News</a></p>
			  </div>
			</div>
		</div>
	{% endfor%}
	</div>
</main>
{% endblock%}

templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Dashboard</h2>
<p>Welcome, {{ user.username }}!</p>
<p><a href="{% url 'logout' %}">Logout</a></p>
</body>
</html>

templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
<main class="container mt-3 mb-5">
	<!-- featured news -->
	<link rel="stylesheet" href="{% static 'style.css' %}">
	<div class="row my-3">
		<!-- Left -->
		<div class="col-md-8">
			<div class="card mb-3">
                 <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{news.title}}</h5>
			    <hr/>
			    <p class="card-text">{{news.detail}}</p>
			  </div>
			  <div class="card-footer">
			  	In <a href="/category/{{news.category.id}}">{{news.category.title}}</a>
			  </div>
			</div>

			<!-- Comments -->
			<div class="card my-4">
				<h6 class="card-header">Add Comment</h6>
				<div class="card-body">
					{% for message in messages%}
					<p class="text-success">{{message}}</p>
					{% endfor %}
					<form method="post" action="/detail/{{news.id}}">
					{% csrf_token %}
						<div class="form-group row">
							<label class="col-md-2">Name<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<input type="text" name="name" required class="form-control" />
							</div>
						</div>
						<div class="form-group row">
							<label class="col-md-2">Email<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<input type="temailext" name="email" required class="form-control" />
							</div>
						</div>
						<div class="form-group row">
							<label class="col-md-2">Comment<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<textarea class="form-control" name="message" required></textarea>
							</div>
						</div>
						<input type="submit" class="btn btn-primary" />
					</form>
				</div>
			</div>
			<!-- Previous Comments -->
			<div class="card my-4">
				<h6 class="card-header">Comments</h6>
				<div class="card-body">
					{% for comment in comments %}
					<blockquote class="blockquote text-right">
					  <p class="mb-0">{{comment.comment}}</p>
					  <footer class="blockquote-footer">{{comment.name}} <cite title="Source Title"> {{comment.email}}</cite></footer>
					</blockquote>
					<hr/>
					{% endfor %}
				</div>
			</div>
		</div>
		<!-- Related News -->
		<div class="col-md-4">
			<h3 class="mb-3 border-bottom pb-1">From this Category</h3>
			<!-- Category Box -->
            {% for news in related_news %}
			<div class="card mb-3 shadow">
			    <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{news.title}}</h5>
			    <hr/> 
			    <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
			  </div>
			</div>
		{% endfor %}
		</div>
	</div>
</main>
{% endblock%}
<script scr="{% static 'script.js' %}"></script>

templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Edit your profile</h2>
<form method="post" enctype="multipart/form-data">
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    {% csrf_token %}
    <button type="submit">Save changes</button>
</form>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
<main class="container mt-3 mb-5">
	<!-- featured news -->
	<link rel="stylesheet" href="{% static 'style.css' %}">
	<div class="row my-3">
		<!-- Left -->
		<div class="col-md-7">
			<div class="card mb-3">
			  <img src="/media/{{first_news.image}}" class="card-img-top" alt="{{first_news.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{first_news.title}}</h5>
			    <hr/>
			    <p class="card-text"><a href="/detail/{{first_news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
			  </div>
			</div>
		</div>
		<!-- Right -->
		<div class="col-md-5" style="max-height: 450px; overflow: auto;">
		{% for news in three_news %}
			<!-- News Box -->
			<div class="card">
			  <div class="row no-gutters">
			    <div class="col-md-4">
			       <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
			    </div>
			    <div class="col-md-8">
			      <div class="card-body">
			        <h5 class="card-title">{{news.title}}</h5>
			        <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
			      </div>
			    </div>
			  </div>
			</div>
			<hr/>
			{% endfor%}
		</div>
	</div>
	<!-- Category Wise News -->
	{% for category in three_categories %}
	<h3 class="border-bottom pb-1"> {{category.title}} <a href="/category/{{category.id}}" 
	class="float-right btn btn-sm btn-dark">In this Category</a></h3>
	<div class="row my-4">
		{% for news in category.news_set.all %}
		{% if forloop.counter < 5 %}
		<!-- News box -->
		<div class="col-md-3">
			<div class="card mb-3 shadow">
		    	<img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{news.title}}</h5>
			    <hr/>
			    <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
			  </div>
			</div>
		</div>
		{% endif %}
		{% endfor %}
	</div>
 {% endfor %}
	<!-- End Single Category -->
</main>
{% endblock%}
<script scr="{% static 'script.js' %}"></script>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3> Hello world!</h3>
<!--categories = ['asd', 'bsd', 'asd2']-->
{% for i in categories %}
    <p>Название: {{ i.title }}</p>
    <p>ID: {{ i.pk }}</p>
{% endfor %}

<h3>This is products</h3>
{% for j in products %}
    <p>Название товара: {{ j }}</p>
    <p>Цена: {{ j.price }}</p>
    <p>Описание: {{ j.description }}</p>
    <p>Количество: {{ j.count }}</p>
    <p>Время создания: {{ j.created_at }}</p>
    <a href="">Buy</a>
    {% empty %}
        <p>Product not found</p>
{% endfor %}
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Register</h2>
<form method="post">
    {{ user_form.as_p }}
    {% csrf_token %}
    <button type="submit">Register</button>
</form>
</body>
</html>

templates/upload_video.html
{% extends 'base.html' %}
{% load static %}

{% block body%}

<div class="container border py-4 my-4 w-75">
    <form action="{% url 'upload' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="title" class="form-label">Title</label>
            <input type="text" name="title" class="form-control" id="title" required>
        </div>

        <div class="mb-3">
            <label for="desc" class="form-label">Description</label>
            <textarea class="form-control" name="desc" id="desc" style="height: 200px;" required></textarea>
        </div>

        <div class="mb-3">
            <label for="filename" class="form-label">Select Video File</label>
            <input type="file" name="fileName" class="form-control" id="filename" accept="video/*" required>
        </div>

        <div class="mb-3">
            <label for="thumb" class="form-label">Select Thumbnail</label>
            <input type="file" name="thumbnail_img" class="form-control" id="thumb" accept="image/*" required>
        </div>

        <div class="mb-3">
            <label for="title" class="form-label">Select Category</label>
            <select class="form-control" name="category">
                <option>Science & Techanology</option>
                <option>Fashion</option>
                <option>Food</option>
                <option>Education</option>
                <option>Blogs</option>
            </select>
        </div>


        <button type="submit" class="btn btn-primary">Upload</button>
    </form>
</div>

{% endblock %}

templates/watch_video.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<div class="row">
  <div class="col-8">
    <div class="container py-2 my-4 w-auto" style="position: absolute; left:100px;">
      <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">

            <video width="750" controls>
              <source src="{% static video.video_file.url %}" type="video/mp4">
            </video>

            </div>

          </div>
        </div>

        <div class="card w-auto">
          <div class="card-body">
            <h5 class="card-title">{{video.title}}</h5>
            <span class="badge rounded-pill bg-info text-dark">{{video.category}}</span>
            <div class="row">
              <div class="col-8">
                <span class="text-muted">{{video.video_views.all.count}} views • {{video.pub_date}}</span>
              </div>
              <div class="col">

              {% if is_liked %}

              <a id="like_btn" class="btn btn-outline-danger mx-3"><span id="count_likes">{{video.likes.all.count}}</span>&nbsp&nbsp<span id="like_icon"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
              </svg>
              </span></a>
              {% else %}

              <a id="like_btn" class="btn btn-outline-danger mx-3"><span id="count_likes">{{video.likes.all.count}}</span>&nbsp&nbsp<span id="like_icon"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                <path d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
              </svg>
              </span></a>
              {% endif %}

          </div>
        </div>
      </div>
    </div>

    <div class="card my-2">
      <div class="card-header">
          <h6><b>DESCRIPTION</b></h6>
      </div>

      <div class="card-body">
        <pre><p>{{video.desc}}</p></pre>
      </div>
    </div>

  </div>
</div>



<div class="col-3" style="margin-left: 0px; width: 400px;">

  <div class="container my-3">
    <h3>Up Next</h3>

    <div class="list-group my-2">
      {% for v in video.user.videopost_set.all %}
      <a href="{% url 'watch_video' v.id %}" class="list-group-item list-group-item-action" aria-current="true">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{v.title}}</h5>
          <small>{{v.pub_date}}</small>
        </div>
        <p class="mb-1">{{v.desc}}</p>
        <small>Donec id elit non mi porta.</small>
      </a>
      {% endfor %}


    </div>

  </div>

  <div class="container my-4">
    <!--Comments of this video-->
    <div class="accordion accordion-flush" id="accordionFlushExample">
      <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingTwo">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
            <b>COMMENTS (<span id='count_comment'>{{comments.count}}</span>)</b>
          </button>
        </h2>
        <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
          <div class="container my-2">
            <ul class="list-group" id="menu">
              {% for comment in comments %}
              <b>{{comment}}</b>  
              <li class="list-group-item">{{comment.comment}}</li>
              {% endfor %}
            </ul>
          </div>
          <div class="accordion-body">
            <form id="my_form">
              <textarea class="form-control" name="comment" id="comment" placeholder="Write your comment..."></textarea>
              <input class="btn btn-outline-success my-3" id="send_btn" type="submit" value="Comment">
            </form>

          </div>
        </div>
      </div>

    </div>
  </div>

</div>
</div>


<script type="text/javascript">

var send_btn = $('#send_btn');
send_btn.on('click', function(event){
  event.preventDefault();
  var comment = $('#comment').val();
  var ul_menu = $('#menu');
  var count_comment = $('#count_comment');

  $.ajax({
    type: 'GET',
    url: '{% url "add_comment" %}',
    data: {comment_text: comment, video_id: '{{video.id}}'},
    dataType: 'json',
    success: function(data){
      if(data.comment)
      {
        var comment_res = data.comment;
        var li_html = "<b>{{request.user}}</b><li class='list-group-item'>"+comment_res+"</li>";

        ul_menu.prepend(li_html);
        count_comment.text(data.count_comments);
        $('#my_form').trigger('reset');

      }

    }

  });
});
</script>


<script type="text/javascript">
var like_btn = $('#like_btn');
like_btn.on('click', function(event){
  event.preventDefault();
  var count_likes = $('#count_likes');
  var like_icon = $('#like_icon');

  $.ajax({
    url: '{% url "add_like" video.id %}',
    data: {},
    dataType: 'json',
    success: function(data){
      if(data.is_liked)
      {
        like_icon.html('<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16"><path d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/></svg>');
        count_likes.text(data.likes_count);
      }
      else
      {

        like_icon.html('<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>');
       count_likes.text(data.likes_count);
     }

   }
 });
});

</script>

{% endblock %}